baseURL: http://thieunguyen.netlify.app/
languageCode: en-us
title: Thieu Nguyen
theme: PaperMod
paginate: 7
defaultContentLanguage: en

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: Thieu Nguyen
  description: Thieu Nguyen blog, a place to share my life/hobby/tech
  keywords: [Blog, Life, Hobby, Technology, Programming]
  author: Thieu Nguyen
  DateFormat: "January 2, 2006"
  defaultTheme: auto
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: true
  comments: true
  disableScrollToTop: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: favicon.ico
    favicon16x16: favicon-16x16.png
    favicon32x32: favicon-32x32.png
    apple_touch_icon: apple-touch-icon.png

  label:
    text: "Thieu Nguyen"
    icon: favicon.ico
    iconHeight: 35

  # home-info mode
  homeInfoParams:
    Title: "Greetings \U0001F44B"
    Content: >
      Welcome to my blog, where I write about life/work/technology/programming, and anything I find interesting.

  socialIcons:
    - name: email
      url: "mailto:thieunguyen.it@gmail.com"
    - name: github
      url: "https://github.com/thieung"
    - name: linkedin
      url: "https://www.linkedin.com/in/thieunv/"

outputs:
  home:
    - HTML
    - JSON
    - RSS

menu:
  main:
    - identifier: about
      name: about
      url: /about/
      weight: 1
    - identifier: categories
      name: categories
      url: /categories/
      weight: 2
    - identifier: archives
      name: archives
      url: /archives/
      weight: 3
    - identifier: search
      name: search
      url: /search/
      weight: 4

enableEmoji: true
