[build]
    publish = "public"
    command = "hugo --gc --minify"

[context.production.environment]
    HUGO_VERSION = "v0.96.0+extended darwin/amd64 BuildDate=unknown"
    HUGO_ENV = "production"
    HUGO_ENABLEGITINFO = "true"
